### ISSUE TITLE
0.6.4.8-SNAPSHOT breaks 2016.1.1

### ISSUE THREAD

**Issue by tml** [headwirecom/aem-ide-tooling-4-intellij#13]
With 0.6.4.8-SNAPSHOT loaded, my IntelliJ no longer starts. The exception thrown is:

```
java.lang.RuntimeException: java.lang.ClassNotFoundException: com.headwire.aem.tooling.intellij.explorer.SlingModuleBuilder PluginClassLoader[com.headwire.aem.tooling.intellij, 0.6.4.8-SNAPSHOT]
    at com.intellij.ide.util.projectWizard.ModuleBuilderFactory.createBuilder(ModuleBuilderFactory.java:35)
    at com.intellij.ide.util.projectWizard.ModuleBuilder.getAllBuilders(ModuleBuilder.java:75)
    at com.intellij.ide.projectWizard.ProjectTypeStep.a(ProjectTypeStep.java:281)
    at com.intellij.ide.projectWizard.ProjectTypeStep.<init>(ProjectTypeStep.java:134)
    at com.intellij.ide.projectWizard.NewProjectWizard.init(NewProjectWizard.java:50)
    at com.intellij.ide.projectWizard.NewProjectWizard.<init>(NewProjectWizard.java:39)
    at com.intellij.ide.actions.NewProjectAction.actionPerformed(NewProjectAction.java:30)
    at com.intellij.ui.components.labels.ActionLink$1.linkSelected(ActionLink.java:64)
    at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:116)
    at com.intellij.ui.components.labels.ActionLink.doClick(ActionLink.java:77)
    at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:287)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:857)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.headwire.aem.tooling.intellij.explorer.SlingModuleBuilder PluginClassLoader[com.headwire.aem.tooling.intellij, 0.6.4.8-SNAPSHOT]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:64)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:63)
    at com.intellij.ide.util.projectWizard.ModuleBuilderFactory.createBuilder(ModuleBuilderFactory.java:32)
    ... 44 more
```

With it complaining about ```com.headwire.aem.tooling.intellij.explorer.SlingModuleBuilder```, I opened `AEM Plugin Tooling.jar` from the zip file and found there is indeed no such class. However, I **do** see a `com.headwire.aem.tooling.intellij.explorer.SlingMavenModuleBuilder` - I am wondering if this is the class, and it's simply been recently renamed?

**Comment by schaefa** [comment]
Yes, this is an issue with a rename where a reference in the Plugin configuration was not updated during the rename. I will post a fixed version asap.

**Comment by schaefa** [comment]
I fixed that issue on my current development release 0.6.9. It is still beta but let me know if this fixed your issue:

https://db.tt/6OQhG9C7

**Comment by schaefa** [comment]
BTW what version of IntelliJ are you using? Normally when this happens you have the choice to disable the plugin and IntelliJ will work normally afterwards but the plugin is not available anymore.

**Comment by dkuntze** [comment]
I had the same issue as @tml but my IntelliJ started properly. However, some of the dialogs wouldn't do anything, etc. @schaefa's 0.6.9 build seems to fix the problems.

**Comment by tml** [comment]
@schaefa - I am using IntelliJ 2016.1.1 - 0.6.9 fixed my problem, thanks!
