### ISSUE TITLE
NPE when deploying bundle

### ISSUE THREAD

**Issue by davidjgonzalez** [headwirecom/aem-ide-tooling-4-intellij#14]
![2016-04-10 at 4 15 pm](https://cloud.githubusercontent.com/assets/1451868/14412757/863a5d14-ff37-11e5-9741-b9425c723728.png)

i noticed this a bit after updating to latest. Let me know if there is a way to collect logs.

**Comment by schaefa** [comment]
This could be an issue of the revamped module model used in the plugin.

Can you click on one of the NullPointerException links in the Event Log, go to Details and post the stack trace?

**Comment by davidjgonzalez** [comment]
```
null
java.lang.NullPointerException
	at com.headwire.aem.tooling.intellij.communication.ContentResourceChangeListener.executeMake(ContentResourceChangeListener.java:230)
	at com.headwire.aem.tooling.intellij.communication.ContentResourceChangeListener.access$100(ContentResourceChangeListener.java:65)
	at com.headwire.aem.tooling.intellij.communication.ContentResourceChangeListener$1.contentsChanged(ContentResourceChangeListener.java:96)
	at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:88)
	at com.intellij.util.EventDispatcher.access$100(EventDispatcher.java:34)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:68)
	at com.sun.proxy.$Proxy16.contentsChanged(Unknown Source)
	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.fireAfter(BulkVirtualFileListenerAdapter.java:65)
	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.after(BulkVirtualFileListenerAdapter.java:56)
	at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:359)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:338)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:226)
	at com.sun.proxy.$Proxy17.after(Unknown Source)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl$5.close(PersistentFSImpl.java:654)
	at com.intellij.openapi.vfs.VirtualFile.setBinaryContent(VirtualFile.java:565)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.write(LoadTextUtil.java:265)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$4.run(FileDocumentManagerImpl.java:432)
	at com.intellij.pom.core.impl.PomModelImpl.guardPsiModificationsIn(PomModelImpl.java:380)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.b(FileDocumentManagerImpl.java:419)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.a(FileDocumentManagerImpl.java:393)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:313)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:292)
	at com.intellij.openapi.application.impl.ApplicationImpl.saveAll(ApplicationImpl.java:1450)
	at com.intellij.ide.actions.SaveAllAction.actionPerformed(SaveAllAction.java:27)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.c(IdeKeyEventDispatcher.java:485)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by schaefa** [comment]
I fixed the issue and will release a fix for it soon. You could try to see if the NPE goes away when you open the Plugin Configuration in the Settings (under tools click on AEM Plugin).

**Comment by schaefa** [comment]
Released version 0.7.0 that contains a fix for that. Please have a spin with it and let me know if that fixed your issue.

**Comment by schaefa** [comment]
Release 0.7.0 with a fix for that. Let me know if that worked for you.

- Andy

**Comment by davidjgonzalez** [comment]
Fixed this NPE.. found another. will open another ticket
