### ISSUE TITLE
NPE when deploying bundle

### ISSUE THREAD

**Issue by davidjgonzalez** [headwirecom/aem-ide-tooling-4-intellij#17]
Got this one after updating to 0.7.0

```
8:35:13 PM Java Class with Errors: This Class: file:///Users/dgonzale/Code/acs/acs-aem-tools/bundle/src/main/java/com/adobe/acs/tools/csv_asset_importer/impl/CsvAssetImporterServlet.java contains error and wasnt compiled because of it
8:36:27 PM Compilation completed with 2 errors and 0 warnings in 8s 468ms
8:36:44 PM NullPointerException: null
```

```
null
java.lang.NullPointerException
    at org.apache.sling.ide.io.NewResourceChangeCommandFactory.normaliseResourceChildren(NewResourceChangeCommandFactory.java:461)
    at org.apache.sling.ide.io.NewResourceChangeCommandFactory.buildResourceAndInfo(NewResourceChangeCommandFactory.java:139)
    at org.apache.sling.ide.io.NewResourceChangeCommandFactory.addFileCommand(NewResourceChangeCommandFactory.java:82)
    at org.apache.sling.ide.io.NewResourceChangeCommandFactory.newCommandForAddedOrUpdated(NewResourceChangeCommandFactory.java:73)
    at com.headwire.aem.tooling.intellij.communication.AbstractDeploymentManager.addFileCommand(AbstractDeploymentManager.java:353)
    at com.headwire.aem.tooling.intellij.communication.AbstractDeploymentManager.publishModule(AbstractDeploymentManager.java:171)
    at com.headwire.aem.tooling.intellij.communication.ServerConnectionManager.deployModule(ServerConnectionManager.java:570)
    at com.headwire.aem.tooling.intellij.communication.ServerConnectionManager.deployModules(ServerConnectionManager.java:551)
    at com.headwire.aem.tooling.intellij.action.DeployToServerAction.doDeploy(DeployToServerAction.java:107)
    at com.headwire.aem.tooling.intellij.action.DeployToServerAction.execute(DeployToServerAction.java:60)
    at com.headwire.aem.tooling.intellij.action.AbstractProjectAction$1.run(AbstractProjectAction.java:106)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

```

**Comment by schaefa** [comment]
Please check out release 1.0 and see if you continue to see that issue.
