### ISSUE TITLE
NPE / IntelliJ 2016.2.4

### ISSUE THREAD

**Issue by krystianpanek** [headwirecom/aem-ide-tooling-4-intellij#21]
I am trying to connect to running AEM instance on 'localhost:8080 / admin:admin' / plugin version (0.7.1 / recent), project generated from archetype: sling / adobe project archetype 10.

```
null
java.lang.NullPointerException
    at com.headwire.aem.tooling.intellij.config.ModuleManagerImpl$InstanceImpl.getUnifiedModules(ModuleManagerImpl.java:152)
    at com.headwire.aem.tooling.intellij.config.ModuleManagerImpl.getUnifiedModules(ModuleManagerImpl.java:97)
    at com.headwire.aem.tooling.intellij.config.ModuleManagerImpl.getUnifiedModules(ModuleManagerImpl.java:92)
    at com.headwire.aem.tooling.intellij.communication.ServerConnectionManager.findUnboundModules(ServerConnectionManager.java:365)
    at com.headwire.aem.tooling.intellij.communication.ServerConnectionManager.checkBinding(ServerConnectionManager.java:359)
    at com.headwire.aem.tooling.intellij.communication.ServerConnectionManager.checkModules(ServerConnectionManager.java:195)
    at com.headwire.aem.tooling.intellij.action.StartRunConnectionAction.doRun(StartRunConnectionAction.java:103)
    at com.headwire.aem.tooling.intellij.action.StartRunConnectionAction.execute(StartRunConnectionAction.java:55)
    at com.headwire.aem.tooling.intellij.action.AbstractProjectAction$1.run(AbstractProjectAction.java:106)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by krystianpanek** [comment]
even after reconnecting with updated settings, error is no longer visible, maven builds seems to be launched, but deploying has no affect. I cannot se both bundles and content on instance.

**Comment by krystianpanek** [comment]
what is more, when I tried to use previous version of IntelliJ, after installing plugin, whole IDE hangs and is no more longer usable

**Comment by schaefa** [comment]
I'll try to have a look into this as soon as my work situation allows for it.

Do you see anything in the AEM Console or the IntelliJ logs that give any indication for it?

**Comment by krystianpanek** [comment]
as pasted above, but I'll try to get more

**Comment by schaefa** [comment]
Please give release 1.0 a shot and let me know if that shows the same issue.
