### ISSUE TITLE
IntelliJ hangs

### ISSUE THREAD

**Issue by Volune** [headwirecom/aem-ide-tooling-4-intellij#43]
IntelliJ hangs when using the "Verify the Current Configuration" or "Connect with Selected Server in Run Mode" operations.

> IntelliJ IDEA 2017.1.3
> Build #IU-171.4424.56, built on May 13, 2017
> JRE: 1.8.0_112-release-736-b21 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0

Plugin version 1.0

[Thread dump](https://github.com/headwirecom/aem-ide-tooling-4-intellij/files/1024569/intellij_dump.txt)

**Comment by schaefa** [comment]
This is an issue with the Thread Handling inside IntelliJ. Can you give Prelease 1.0.1 a spin.

**Comment by Volune** [comment]
Reproduced with 1.0.1-beta
[Thread dump](https://github.com/headwirecom/aem-ide-tooling-4-intellij/files/1057468/intellij_dump2.txt)

**Comment by schaefa** [comment]
Hi

Looking at the latest Thread Dump I don't see a block. If you search for 'AWT-EventQueue-0' then you find that the verification is accessing the remote JCR repository and working though it.

Depending on the size of you project this can take a while but is necessary to make sure that the cache and the remote AEM server are in sync. This can take a while during which the Plugin is unresponsive.

I will have a look into how to run the Verification and the Start Debug / Run Connection in the background. That requires some changes including tests to avoid running the task multiple times, keep it visually pending and to prevent the user from Deploying anything until connection is established.

Can you open the AEM Console, set it to "Debug and Up" and see if you see any progress listed there?
If so let me know how long it takes for you to end the Verification.

Thanks - Andy

**Comment by Volune** [comment]
Hi. I have nothing in the AEM console, all the IntelliJ UI is hanging and unresponsive.

Looks like it's something with the logger configuration for jackrabbit, with the logger hanging while writing.
```
"AWT-EventQueue-0 2017.1.4#IU-171.4694.23 IDEA, eap:false, os:Windows 10 10.0, java-version:JetBrains s.r.o 1.8.0_112-release-736-b21" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE
 (in native)
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
	at java.io.PrintStream.write(PrintStream.java:480)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
	at ch.qos.logback.core.joran.spi.ConsoleTarget$1.write(ConsoleTarget.java:37)
	at ch.qos.logback.core.encoder.LayoutWrappingEncoder.doEncode(LayoutWrappingEncoder.java:131)
	at ch.qos.logback.core.OutputStreamAppender.writeOut(OutputStreamAppender.java:187)
	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:212)
	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:100)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:48)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	at ch.qos.logback.classic.Logger.debug(Logger.java:482)
	at org.apache.jackrabbit.jcr2spi.ItemCacheImpl.cacheItem(ItemCacheImpl.java:121)
	at org.apache.jackrabbit.jcr2spi.ItemCacheImpl.itemCreated(ItemCacheImpl.java:71)
	at org.apache.jackrabbit.jcr2spi.ItemImpl.notifyCreated(ItemImpl.java:375)
	at org.apache.jackrabbit.jcr2spi.ItemImpl.<init>(ItemImpl.java:86)
	at org.apache.jackrabbit.jcr2spi.PropertyImpl.<init>(PropertyImpl.java:63)
	at org.apache.jackrabbit.jcr2spi.ItemManagerImpl.createPropertyInstance(ItemManagerImpl.java:335)
	at org.apache.jackrabbit.jcr2spi.ItemManagerImpl.created(ItemManagerImpl.java:353)
	at org.apache.jackrabbit.jcr2spi.state.AbstractItemStateFactory.notifyCreated(AbstractItemStateFactory.java:74)
	at org.apache.jackrabbit.jcr2spi.state.TransientISFactory.created(TransientISFactory.java:153)
	at org.apache.jackrabbit.jcr2spi.state.AbstractItemStateFactory.notifyCreated(AbstractItemStateFactory.java:74)
	at org.apache.jackrabbit.jcr2spi.state.WorkspaceItemStateFactory.createPropertyState(WorkspaceItemStateFactory.java:390)
	at org.apache.jackrabbit.jcr2spi.state.WorkspaceItemStateFactory.createPropertyState(WorkspaceItemStateFactory.java:180)
	at org.apache.jackrabbit.jcr2spi.state.TransientISFactory.createPropertyState(TransientISFactory.java:116)
	at org.apache.jackrabbit.jcr2spi.hierarchy.PropertyEntryImpl.doResolve(PropertyEntryImpl.java:69)
	at org.apache.jackrabbit.jcr2spi.hierarchy.HierarchyEntryImpl.resolve(HierarchyEntryImpl.java:134)
	at org.apache.jackrabbit.jcr2spi.hierarchy.HierarchyEntryImpl.getItemState(HierarchyEntryImpl.java:253)
	at org.apache.jackrabbit.jcr2spi.hierarchy.PropertyEntryImpl.getItemState(PropertyEntryImpl.java:35)
	at org.apache.jackrabbit.jcr2spi.ItemManagerImpl.getItem(ItemManagerImpl.java:199)
	at org.apache.jackrabbit.jcr2spi.LazyItemIterator.prefetchNext(LazyItemIterator.java:138)
	at org.apache.jackrabbit.jcr2spi.LazyItemIterator.next(LazyItemIterator.java:251)
	at org.apache.jackrabbit.jcr2spi.LazyItemIterator.nextProperty(LazyItemIterator.java:163)
	at org.apache.sling.ide.impl.vlt.JcrCommand.nodeToResource(JcrCommand.java:111)
	at org.apache.sling.ide.impl.vlt.ListTreeCommand.addChildren(ListTreeCommand.java:76)
	at org.apache.sling.ide.impl.vlt.ListTreeCommand.execute0(ListTreeCommand.java:54)
	at org.apache.sling.ide.impl.vlt.ListTreeCommand.execute0(ListTreeCommand.java:1)
	at org.apache.sling.ide.impl.vlt.JcrCommand.execute(JcrCommand.java:68)
	at org.apache.sling.ide.transport.TracingCommand.execute(TracingCommand.java:45)
	at org.apache.sling.ide.impl.vlt.VltNodeTypeFactory.init(VltNodeTypeFactory.java:48)
	at org.apache.sling.ide.impl.vlt.VltNodeTypeRegistry.<init>(VltNodeTypeRegistry.java:39)
	at org.apache.sling.ide.impl.vlt.VltRepository.loadNodeTypeRegistry(VltRepository.java:82)
	at org.apache.sling.ide.impl.vlt.VltRepository.connect(VltRepository.java:77)
	at org.apache.sling.ide.impl.vlt.VltRepositoryFactory.connectRepository(VltRepositoryFactory.java:69)
	at com.headwire.aem.tooling.intellij.eclipse.ServerUtil.connectRepository(ServerUtil.java:93)
	at com.headwire.aem.tooling.intellij.communication.ServerConnectionManager.obtainRepository(ServerConnectionManager.java:456)
	at com.headwire.aem.tooling.intellij.action.VerifyConfigurationAction.doVerify(VerifyConfigurationAction.java:146)
	at com.headwire.aem.tooling.intellij.action.VerifyConfigurationAction.execute(VerifyConfigurationAction.java:66)
	at com.headwire.aem.tooling.intellij.action.AbstractProjectAction.actionPerformed(AbstractProjectAction.java:120)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:215)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:232)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:188)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:154)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:325)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:651)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

An async appender could be useful here. Any idea where I can find the logger configuration?

**Comment by schaefa** [comment]
During debugging I ran into an issue where Jackrabbit ended in an endless loop. Can you tail the idea.log file and tell me if that one is dead or if the log file is appended.

I don't know how the Jackrabbit logging can be configured but even if that can be configured and we have an endless loop that will probably not fix the endless loop.

**Comment by schaefa** [comment]
Investigating another issue I maybe discovered the cause for the issue.

Could you please install the latest pre-release (https://github.com/headwirecom/aem-ide-tooling-4-intellij/releases/tag/r1.0.2-beta-1) and see if that fixes your issue.

**Comment by schaefa** [comment]
Actually I jus posted a release: https://github.com/headwirecom/aem-ide-tooling-4-intellij/releases/tag/r1.0.2-beta-2 that should fix your issue.

Let me know if that does the trick for you.

**Comment by Volune** [comment]
Tried 1.0.2-beta-2.
IJ freezed for around 30sec during the Verify, then worked again. Connect worked too. It may be useful to move some of the tasks to another thread, not the UI thread.

Issue solved. Thank you.
