### ISSUE TITLE
Cant connect to server

### ISSUE THREAD

**Issue by Iskz** [headwirecom/aem-ide-tooling-4-intellij#50]
Can't connect to server Using AEM IDE Tooling for Intellij Idea.
Happens on Mac OS High Sierra

org/eclipse/core/runtime/Plugin
java.lang.NoClassDefFoundError: org/eclipse/core/runtime/Plugin
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:272)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:268)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:237)
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:138)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:76)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.sling.ide.impl.vlt.VltRepository.<init>(VltRepository.java:53)
	at org.apache.sling.ide.impl.vlt.VltRepositoryFactory.connectRepository(VltRepositoryFactory.java:68)
	at com.headwire.aem.tooling.intellij.eclipse.ServerUtil.connectRepository(ServerUtil.java:93)
	at com.headwire.aem.tooling.intellij.communication.ServerConnectionManager.obtainRepository(ServerConnectionManager.java:456)
	at com.headwire.aem.tooling.intellij.action.VerifyConfigurationAction.doVerify(VerifyConfigurationAction.java:146)
	at com.headwire.aem.tooling.intellij.action.AbstractProjectAction$2.run(AbstractProjectAction.java:144)
	at com.headwire.aem.tooling.intellij.util.ExecutionUtil$1.run(ExecutionUtil.java:41)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:314)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.eclipse.core.runtime.Plugin PluginClassLoader[com.headwire.aem.tooling.intellij, 1.0.1] com.intellij.ide.plugins.cl.PluginClassLoader@7a2b3ff2
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 more

java.lang.NoClassDefFoundError: org/apache/sling/ide/impl/vlt/Activator
	at org.apache.sling.ide.impl.vlt.VltRepository.<init>(VltRepository.java:53)
	at org.apache.sling.ide.impl.vlt.VltRepositoryFactory.connectRepository(VltRepositoryFactory.java:68)
	at com.headwire.aem.tooling.intellij.eclipse.ServerUtil.connectRepository(ServerUtil.java:93)
	at com.headwire.aem.tooling.intellij.communication.ServerConnectionManager.obtainRepository(ServerConnectionManager.java:456)
	at com.headwire.aem.tooling.intellij.communication.ServerConnectionManager.obtainOSGiClient(ServerConnectionManager.java:426)
	at com.headwire.aem.tooling.intellij.action.StartRunConnectionAction.doRun(StartRunConnectionAction.java:77)
	at com.headwire.aem.tooling.intellij.action.StartRunConnectionAction.execute(StartRunConnectionAction.java:43)
	at com.headwire.aem.tooling.intellij.action.AbstractProjectAction$1.run(AbstractProjectAction.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by rkorrelboom** [comment]
+1, also on Mac OS High Sierra

**Comment by schaefa** [comment]
I am sorry but I did not upgrade to High Sierra yet so I cannot test, evaluate or even speculate about this. As soon as I did the upgrade I will test it but for now I don't have the hardware nor the time to do so in the near future.

**Comment by SBPrakash** [comment]
+1, also on Mac OS High Sierra

**Comment by SBPrakash** [comment]
@schaefa could you please fix this issue.. I am crying without this plugin working

**Comment by schaefa** [comment]
I finally upgraded to High Sierra and could test the issue.

This is an issue because the Sling IDE code is an OSGi plugin and they use Eclipse code to implement that. I will try to remedy that situation by patching the JAR file and removing any Eclipse code. As soon as I know more I will post an ETA or release a beta version with that fix in it.

**Comment by schaefa** [comment]
I uploaded a beta release of the 1.0.2 plugin which should fix the issue on Mac OS X High Sierra.

If you use another OS or other Mac OS X version than High Sierra please give it a spin to see if we regressed - thanks.

**Comment by SBPrakash** [comment]
Thanks for quick updated release.. keep you posted if there is more issues

**Comment by SBPrakash** [comment]
@schaefa getting the error while upload the plugin from disk as "Fail to load plugin descriptor from file"

**Comment by Iskz** [comment]
@schaefa Seems like the plugin error was resolved. But the second half is still there.

org/apache/sling/ide/impl/vlt/Activator
java.lang.NoClassDefFoundError: org/apache/sling/ide/impl/vlt/Activator
	at org.apache.sling.ide.impl.vlt.VltRepository.<init>(VltRepository.java:53)
	at org.apache.sling.ide.impl.vlt.VltRepositoryFactory.connectRepository(VltRepositoryFactory.java:68)
	at com.headwire.aem.tooling.intellij.eclipse.ServerUtil.connectRepository(ServerUtil.java:93)
	at com.headwire.aem.tooling.intellij.communication.ServerConnectionManager.obtainRepository(ServerConnectionManager.java:467)
	at com.headwire.aem.tooling.intellij.communication.ServerConnectionManager.obtainOSGiClient(ServerConnectionManager.java:437)
	at com.headwire.aem.tooling.intellij.communication.ServerConnectionManager.checkAndUpdateSupportBundle(ServerConnectionManager.java:388)
	at com.headwire.aem.tooling.intellij.action.DeployToServerAction.doDeploy(DeployToServerAction.java:81)
	at com.headwire.aem.tooling.intellij.action.DeployToServerAction.execute(DeployToServerAction.java:52)
	at com.headwire.aem.tooling.intellij.action.AbstractProjectAction$1.run(AbstractProjectAction.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by schaefa** [comment]
I am sorry but I uploaded the wrong file. I replaced the file on the release (now the file is named 'AEM IDE Tooling 4 IntelliJ.zip'). Please download and install this one and give it a spin.

Thanks - Andy

**Comment by Iskz** [comment]
1:26:28 AM Cannot Connect to Repository: Cannot Connect to Repository with Name 'Default' due to an Exception 'com.headwire.aem.tooling.intellij.eclipse.stub.CoreException'

Seems like all I can get from the errors.

**Comment by schaefa** [comment]
@Iskz Updated the Plugin to include a logging statement. You need to open the IntelliJ Logs (Help -> Show Log in Finder) to see the stack trace. I could create an Core Exception with a wrong password so please make sure you setting are correct.

**Comment by SBPrakash** [comment]
As @Iskz  said, I am also getting this error.. 

2017-11-21 09:45:11,254 [ 338206]   WARN - llij.ide.plugins.PluginManager - Notification Exception 
com.headwire.aem.tooling.intellij.eclipse.stub.CoreException
	at com.headwire.aem.tooling.intellij.eclipse.ServerUtil.connectRepository(ServerUtil.java:97)
	at com.headwire.aem.tooling.intellij.communication.ServerConnectionManager.obtainRepository(ServerConnectionManager.java:463)
	at com.headwire.aem.tooling.intellij.action.VerifyConfigurationAction.doVerify(VerifyConfigurationAction.java:146)
	at com.headwire.aem.tooling.intellij.action.AbstractProjectAction$2.run(AbstractProjectAction.java:144)
	at com.headwire.aem.tooling.intellij.util.ExecutionUtil$1.run(ExecutionUtil.java:41)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at org.apache.sling.ide.jcr.RepositoryUtils.getRepositoryAddress(RepositoryUtils.java:98)
	at org.apache.sling.ide.jcr.RepositoryUtils.getRepository(RepositoryUtils.java:52)
	at org.apache.sling.ide.impl.vlt.VltRepository.connect(VltRepository.java:70)
	at org.apache.sling.ide.impl.vlt.VltRepositoryFactory.connectRepository(VltRepositoryFactory.java:69)
	at com.headwire.aem.tooling.intellij.eclipse.ServerUtil.connectRepository(ServerUtil.java:93)
	... 24 more

**Comment by Iskz** [comment]
Here are my logs
2017-11-21 10:42:49,249 [ 213552]   WARN - llij.ide.plugins.PluginManager - Notification Exception 
com.headwire.aem.tooling.intellij.eclipse.stub.CoreException
	at com.headwire.aem.tooling.intellij.eclipse.ServerUtil.connectRepository(ServerUtil.java:97)
	at com.headwire.aem.tooling.intellij.communication.ServerConnectionManager.obtainRepository(ServerConnectionManager.java:463)
	at com.headwire.aem.tooling.intellij.action.VerifyConfigurationAction.doVerify(VerifyConfigurationAction.java:146)
	at com.headwire.aem.tooling.intellij.action.AbstractProjectAction$2.run(AbstractProjectAction.java:144)
	at com.headwire.aem.tooling.intellij.util.ExecutionUtil$1.run(ExecutionUtil.java:41)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:314)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at org.apache.sling.ide.jcr.RepositoryUtils.getRepositoryAddress(RepositoryUtils.java:98)
	at org.apache.sling.ide.jcr.RepositoryUtils.getRepository(RepositoryUtils.java:52)
	at org.apache.sling.ide.impl.vlt.VltRepository.connect(VltRepository.java:70)
	at org.apache.sling.ide.impl.vlt.VltRepositoryFactory.connectRepository(VltRepositoryFactory.java:69)
	at com.headwire.aem.tooling.intellij.eclipse.ServerUtil.connectRepository(ServerUtil.java:93)
	... 24 more

**Comment by schaefa** [comment]
Third time a charm?

I fixed an issue with the reflection I use in the Activator patch. It should work now even when the connection fails. Please have a look at the beta release to update and test.

Thanks

**Comment by Iskz** [comment]
Beta release was updated 4 days ago. is this the correct one ?

**Comment by schaefa** [comment]
Yeah. I use the same release just replace the artifact. That said I mention the updates in the release text body. Unfortunately any edits to the release it not tracked.

**Comment by Iskz** [comment]
Noted.
Able to connect but unable to push.

2017-11-22 08:23:14,258 [ 417001]  ERROR - intellij.openapi.progress.Task - org/apache/jackrabbit/vault/util/DocViewNode 
java.lang.NoClassDefFoundError: org/apache/jackrabbit/vault/util/DocViewNode
	at org.apache.sling.ide.impl.vlt.serialization.ContentXmlHandler.startElement(ContentXmlHandler.java:92)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
	at org.apache.sling.ide.impl.vlt.serialization.VltSerializationManager.readSerializationData(VltSerializationManager.java:245)
	at org.apache.sling.ide.io.NewResourceChangeCommandFactory.buildResourceProxy(NewResourceChangeCommandFactory.java:429)
	at org.apache.sling.ide.io.NewResourceChangeCommandFactory.buildResourceProxyForPlainFileOrFolder(NewResourceChangeCommandFactory.java:336)
	at org.apache.sling.ide.io.NewResourceChangeCommandFactory.buildResourceAndInfo(NewResourceChangeCommandFactory.java:199)
	at org.apache.sling.ide.io.NewResourceChangeCommandFactory.addFileCommand(NewResourceChangeCommandFactory.java:82)
	at org.apache.sling.ide.io.NewResourceChangeCommandFactory.newCommandForAddedOrUpdated(NewResourceChangeCommandFactory.java:73)
	at com.headwire.aem.tooling.intellij.communication.AbstractDeploymentManager.addFileCommand(AbstractDeploymentManager.java:351)
	at com.headwire.aem.tooling.intellij.communication.AbstractDeploymentManager.ensureParentIsPublished(AbstractDeploymentManager.java:293)
	at com.headwire.aem.tooling.intellij.communication.AbstractDeploymentManager.publishModule(AbstractDeploymentManager.java:172)
	at com.headwire.aem.tooling.intellij.communication.ServerConnectionManager.deployModule(ServerConnectionManager.java:534)
	at com.headwire.aem.tooling.intellij.action.DeployToServerAction.doDeploy(DeployToServerAction.java:96)
	at com.headwire.aem.tooling.intellij.action.DeployToServerAction.execute(DeployToServerAction.java:52)
	at com.headwire.aem.tooling.intellij.action.AbstractProjectAction$1.run(AbstractProjectAction.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-11-22 08:23:14,258 [ 417001]  ERROR - intellij.openapi.progress.Task - IntelliJ IDEA 2017.2.6  Build #IU-172.4574.11 
2017-11-22 08:23:14,258 [ 417001]  ERROR - intellij.openapi.progress.Task - JDK: 1.8.0_152-release 
2017-11-22 08:23:14,258 [ 417001]  ERROR - intellij.openapi.progress.Task - VM: OpenJDK 64-Bit Server VM 
2017-11-22 08:23:14,258 [ 417001]  ERROR - intellij.openapi.progress.Task - Vendor: JetBrains s.r.o 
2017-11-22 08:23:14,258 [ 417001]  ERROR - intellij.openapi.progress.Task - OS: Mac OS X 
2017-11-22 08:23:14,258 [ 417001]  ERROR - intellij.openapi.progress.Task - Last Action: AEM.Deploy.Action

**Comment by SBPrakash** [comment]
@schaefa I am also able to connect to server but not able to push anything. Even when I update the plugin my IntelliJ got hanged. I clear all the existing  config  to make it work.

**Comment by schaefa** [comment]
Found an issue with outdated dependencies and fix it. The beta release has the updated plugin ZIP file. Please give it a try - thanks.

**Comment by Iskz** [comment]
![image](https://user-images.githubusercontent.com/8488636/33141801-3b848120-cfef-11e7-8b35-093fb84e7bf6.png)

Hi @schaefa, not sure why i'm not seeing any Build Modules here.

**Comment by Iskz** [comment]
Sorry, please ignore my previous message. 

Verified that its all working now !

Great job !

**Comment by schaefa** [comment]
Cool, thanks. I will wait a few more days and then release 1.0.3.
