### ISSUE TITLE
Run Server Configuration produces org/apache/sling/ide/impl/vlt/Activator Error

### ISSUE THREAD

**Issue by SakuraSensei** [headwirecom/aem-ide-tooling-4-intellij#54]
Good day everyone,

after  I installed the plugin and I'd setup the server configuration I setup aemdc with the following settings:

# Source folders
SOURCE_FOLDER=/Users/foo/aemdc-0.10.2/bin
SOURCE_TYPES_FOLDER={{SOURCE_FOLDER}}

# Target folders
TARGET_UI_FOLDER=ui.apps/src/main/content/jcr_root
TARGET_PROJECT_APPS_FOLDER=aem6.4-pr
TARGET_PROJECT_CONF_FOLDER=aem6.4-pr
TARGET_PROJECT_DESIGN_FOLDER=aem6.4-pr
TARGET_PROJECT_ROOT={{TARGET_UI_FOLDER}}/apps/{{TARGET_PROJECT_APPS_FOLDER}}
TARGET_OSGI_SUBFOLDER=/configuration
TARGET_JAVA_FOLDER=core/src/main/java
TARGET_JAVA_PACKAGE=com.example.aem6.4-pr
TARGET_JAVA_PACKAGE_FOLDER={{TARGET_JAVA_FOLDER}}/com/example/aem6/4-pr
TARGET_JAVA_MODEL_SUBPACKAGE=models

# Other config properties
FILES_WITH_PLACEHOLDERS_EXTENSIONS=xml,java,html,jsp,js,css,properties
FORBIDDEN_TEMPLATE_TYPES=.git,.settings,target,help,.idea
EXISTING_DESTINATION_RESOURCES_REPLACEMENT=MERGE
LOG_LEVEL=INFO

What I'd done next was that I started the server configuration in run mode and get the following error:
org/apache/sling/ide/impl/vlt/Activator
java.lang.NoClassDefFoundError: org/apache/sling/ide/impl/vlt/Activator
	at org.apache.sling.ide.impl.vlt.VltRepository.<init>(VltRepository.java:53)
	at org.apache.sling.ide.impl.vlt.VltRepositoryFactory.connectRepository(VltRepositoryFactory.java:68)
	at com.headwire.aem.tooling.intellij.eclipse.ServerUtil.connectRepository(ServerUtil.java:93)
	at com.headwire.aem.tooling.intellij.communication.ServerConnectionManager.obtainRepository(ServerConnectionManager.java:456)
	at com.headwire.aem.tooling.intellij.communication.ServerConnectionManager.obtainOSGiClient(ServerConnectionManager.java:426)
	at com.headwire.aem.tooling.intellij.action.StartRunConnectionAction.doRun(StartRunConnectionAction.java:77)

Could you please give me a hint what to try next.
Please get back to me in case you need more information.

Best regards
Miriam

**Comment by schaefa** [comment]
Are you using the latest 1.0.3-beta? If not then give that one a spin: https://github.com/headwirecom/aem-ide-tooling-4-intellij/releases
