### ISSUE TITLE
Not able find AEM modules in edit build configuration. 

### ISSUE THREAD

**Issue by nbsharath** [headwirecom/aem-ide-tooling-4-intellij#63]
I am not able to find the AEM modules to add them to server. I am getting below error. 
Below log will provide all the information. I am getting this error on open and when i try to import

2019-08-14 10:06:25,657 [ 131465]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2018.3.3  Build #IC-183.5153.38 
2019-08-14 10:06:25,657 [ 131465]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_152-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-08-14 10:06:25,657 [ 131465]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 10 
2019-08-14 10:06:25,658 [ 131466]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: AEM IDE Tooling 4 IntelliJ version: 1.0.3.2 
2019-08-14 10:06:25,658 [ 131466]  ERROR - llij.ide.plugins.PluginManager - Last Action: AEM.DC.Panel.Action 
2019-08-14 10:06:25,890 [ 131698]  ERROR - llij.ide.plugins.PluginManager - Argument for @NotNull parameter 'relPath' of com/intellij/openapi/vfs/VirtualFile.findFileByRelativePath must not be null 
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'relPath' of com/intellij/openapi/vfs/VirtualFile.findFileByRelativePath must not be null
	at com.intellij.openapi.vfs.VirtualFile.$$$reportNull$$$0(VirtualFile.java)
	at com.intellij.openapi.vfs.VirtualFile.findFileByRelativePath(VirtualFile.java)
	at com.headwire.aem.tooling.intellij.ui.AemdcConfigurationDialog.setUpDialog(AemdcConfigurationDialog.java:173)
	at com.headwire.aem.tooling.intellij.ui.AemdcConfigurationDialog.<init>(AemdcConfigurationDialog.java:125)
	at com.headwire.aem.tooling.intellij.explorer.AemdcPanel.showDialog(AemdcPanel.java:176)
	at com.headwire.aem.tooling.intellij.explorer.AemdcPanel.display(AemdcPanel.java:133)
	at com.headwire.aem.tooling.intellij.action.AemDcPanelAction.toggle(AemDcPanelAction.java:82)
	at com.headwire.aem.tooling.intellij.action.AemDcPanelAction.actionPerformed(AemDcPanelAction.java:58)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:258)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:275)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:184)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:148)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:410)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:664)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

![image](https://user-images.githubusercontent.com/23138533/62994940-193a8b00-be7c-11e9-88f7-2aa3b576cadd.png)

 - OS: Windows 10 
 - JDK: 1.8.0_152-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o
 - IntelliJ IDEA 2018.3.3  Build #IC-183.5153.38 
 - Plugin : AEM IDE Tooling 4 IntelliJ version: 1.0.3.2

**Comment by schaefa** [comment]
I'll have a look into this. If you can check if that is still an issue with 1.0.3.5-beta that would be helpful.

**Comment by nbsharath** [comment]
Got resolved with latest build.
