### ISSUE TITLE
Error when plugin is active

### ISSUE THREAD

**Issue by visiongeist** [headwirecom/aem-ide-tooling-4-intellij#8]
Hi guys,

I keep getting a popup in IntelliJ when the plugin is active. 
This is the stack trace. Any ideas why?

Thanks,
Damien

```
2015-08-13 09:47:20,827 [ 262539]   INFO - plication.impl.ApplicationImpl - Saving application settings failed 
com.intellij.openapi.components.StateStorageException: java.io.IOException:  not found
	at com.intellij.openapi.components.impl.stores.XmlElementStorage$XmlElementStorageSaveSession.save(XmlElementStorage.java:294)
	at com.intellij.openapi.components.impl.stores.StateStorageManagerImpl$StateStorageSaveSession.save(StateStorageManagerImpl.java:521)
	at com.intellij.openapi.components.impl.stores.ComponentStoreImpl.executeSave(ComponentStoreImpl.java:383)
	at com.intellij.openapi.components.impl.stores.ComponentStoreImpl$SaveSessionImpl.save(ComponentStoreImpl.java:410)
	at com.intellij.openapi.components.impl.stores.StoreUtil.doSave(StoreUtil.java:48)
	at com.intellij.openapi.application.impl.ApplicationImpl._saveSettings(ApplicationImpl.java:1406)
	at com.intellij.openapi.application.impl.ApplicationImpl.saveSettings(ApplicationImpl.java:1445)
	at com.intellij.ide.SaveAndSyncHandlerImpl.saveProjectsAndDocuments(SaveAndSyncHandlerImpl.java:154)
	at com.intellij.ide.SaveAndSyncHandlerImpl$3.onFrameDeactivated(SaveAndSyncHandlerImpl.java:103)
	at com.intellij.ide.FrameStateManagerImpl.a(FrameStateManagerImpl.java:87)
	at com.intellij.ide.FrameStateManagerImpl.access$500(FrameStateManagerImpl.java:32)
	at com.intellij.ide.FrameStateManagerImpl$2$1.run(FrameStateManagerImpl.java:72)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:318)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.io.IOException:  not found
	at com.intellij.openapi.components.impl.stores.StorageUtil.a(StorageUtil.java:244)
	at com.intellij.openapi.components.impl.stores.StorageUtil.writeFile(StorageUtil.java:180)
	at com.intellij.openapi.components.impl.stores.FileBasedStorage$FileSaveSession.doSave(FileBasedStorage.java:153)
	at com.intellij.openapi.components.impl.stores.XmlElementStorage$XmlElementStorageSaveSession.save(XmlElementStorage.java:290)
	... 31 more
```

**Comment by schaefa** [comment]
This is quite outdated and so I close it for now.
